// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EventsEmit(eventName, ...data) {
  return window.runtime.EventsEmit(eventName, ...data);
}

export function EventsOn(eventName, callback) {
  return window.runtime.EventsOn(eventName, callback);
}

export function EventsOnce(eventName, callback) {
  return window.runtime.EventsOnce(eventName, callback);
}

export function EventsOff(eventName, ...additionalEventNames) {
  return window.runtime.EventsOff(eventName, ...additionalEventNames);
}

export function Quit() {
  return window.runtime.Quit();
}

export function WindowSetTitle(title) {
  return window.runtime.WindowSetTitle(title);
}
