// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1: string): Promise<string>;

export function GetStartupFileContent(): Promise<string[] | null>;

export function OpenFileDialog(): Promise<string>;

export function SaveFileDialog(arg1: string): Promise<string>;

export function ReadFile(arg1: string): Promise<string>;

export function WriteFile(arg1: string, arg2: string): Promise<void>;

export function AskDialog(arg1: string, arg2: string): Promise<boolean>;

export function InfoDialog(arg1: string, arg2: string): Promise<void>;

export function SetTitle(arg1: string): Promise<void>;

export function Quit(): Promise<void>;

export function LoadSettings(): Promise<string>;

export function SaveSettings(arg1: string): Promise<void>;
