// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskDialog(arg1, arg2) {
  return window['go']['main']['App']['AskDialog'](arg1, arg2);
}

export function GenerateImageWithAI(arg1, arg2) {
  return window['go']['main']['App']['GenerateImageWithAI'](arg1, arg2);
}

export function GetStartupFileContent() {
  return window['go']['main']['App']['GetStartupFileContent']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InfoDialog(arg1, arg2) {
  return window['go']['main']['App']['InfoDialog'](arg1, arg2);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SaveFileDialogForExport(arg1, arg2) {
  return window['go']['main']['App']['SaveFileDialogForExport'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetTitle(arg1) {
  return window['go']['main']['App']['SetTitle'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}

export function WriteFileBase64(arg1, arg2) {
  return window['go']['main']['App']['WriteFileBase64'](arg1, arg2);
}
