// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskDialog(arg1:string,arg2:string):Promise<boolean>;

export function SelectDirectoryDialog():Promise<string>;

export function GenerateImageWithAI(arg1:string,arg2:string):Promise<string>;

export function GetStartupFileContent():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function InfoDialog(arg1:string,arg2:string):Promise<void>;

export function LoadSettings():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function Quit():Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SaveFileDialogForExport(arg1:string,arg2:string):Promise<string>;

export function SaveSettings(arg1:string):Promise<void>;

export function SetTitle(arg1:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;

export function WriteFileBase64(arg1:string,arg2:string):Promise<void>;
